### ISSUE TITLE
Add gnm_random_graph functions

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#167]
### What is the expected enhancement?

While retworkx has a random G_n,p graph functions there are some use cases for a random G_n,m graphs. Specifically: https://github.com/Qiskit/qiskit-terra/blob/01ded73d1ded2342e39bc22d994ba0b50ffc8de7/test/python/transpiler/test_token_swapper.py#L105 We should add this to retworkx too. This could be part of #150 but opening as a a separate issue since it's a feature gap for terra (well terra's tests at least).

**Comment by MoAllabbad** [comment]
Should this return an undirected graph? terra's usage doesn't seem to care.

**Comment by mtreinish** [comment]
This would be to add both a an undirected and directed function, for example like: https://github.com/Qiskit/retworkx/blob/master/src/lib.rs#L1452 and https://github.com/Qiskit/retworkx/blob/master/src/lib.rs#L1536

The terra use case I linked to just expects an undirected graph (that's the default type from networkx). But the work to implement the function is more or less identical so might as well add both.

**Comment by MoAllabbad** [comment]
Sounds good! I'll start working on this if that's ok.

**Comment by mtreinish** [comment]
Sure, of course. I just assigned the issue to you.

**Comment by MoAllabbad** [comment]
Thanks. On a side note. The implementation of retwokx's gnp doesn't accept exact 0 and 1 probabilities, whereas networkx does, returning empty or full graphs respectively. I'm not sure of the significance of that.

**Comment by mtreinish** [comment]
> Thanks. On a side note. The implementation of retwokx's gnp doesn't accept exact 0 and 1 probabilities, whereas networkx does, returning empty or full graphs respectively. I'm not sure of the significance of that.

Oh, that's a fair point. It's just an oversight really. I'm not sure if there is a use case for it since you can just create an empty and full graph directly pretty easily, but it does seem like something worth adding. Feel free to open an issue or push a PR to fix it and we can go from there.

**Comment by MoAllabbad** [comment]
> Oh, that's a fair point. It's just an oversight really. I'm not sure if there is a use case for it since you can just create an empty and full graph directly pretty easily, but it does seem like something worth adding. Feel free to open an issue or push a PR to fix it and we can go from there.

Opened an issue [#172](https://github.com/Qiskit/retworkx/issues/172) and should push a PR soon.
