### ISSUE TITLE
Missing method to remove multiple edges simultaneously in PyGraph class

### ISSUE THREAD

**Issue by seatonullberg** [Qiskit/retworkx#177]
### What is the expected enhancement?
A method will be added to the PyGraph class which can simultaneously remove multiple edges.

The PyGraph class has the method `remove_nodes_from` which accepts multiple indices to remove in a single call. However, there is no corresponding `remove_edges_from` to remove multiple edges. Are there any implementation details preventing this method from existing?

**Comment by mtreinish** [comment]
Oh, that's a good idea. This was really more of an oversight than anything else. It should be fairly straightforward to add. Just have a method that takes in a Vec of tuples for the node indices of the edge and iterate over that.
