### ISSUE TITLE
Add bidirectional flag to existing generator functions

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#184]
### What is the expected enhancement?

The existing directed_* generator functions in https://github.com/Qiskit/retworkx/blob/master/src/generators.rs only have an option to add a single edge. But it could be useful to add edges in both directions. While this is essentially the same as a undirected version of the function there are use cases where you could want bidirectional edges added to a directed graph generatore. For example a bidirectional path graph: `a <-> b <-> c` instead of just `a -> b -> c` that exists now. This would be to add a new boolean kwarg to the existing (and potential future) directed generator functions to set adding bidirectional edges.

This is related to #150 but self contained enhancement for the existing generator functions rather than adding new functions.

**Comment by darknight009** [comment]
Can I work on this?

**Comment by mtreinish** [comment]
@darknight009 sure go ahead. I've assigned the issue to you.

**Comment by darknight009** [comment]
What is the default expected behavior of bidirectionality?  Should it be set to "false" for directed_* generators?

**Comment by mtreinish** [comment]
Yeah, it should be default false. By default things should not be bidirectional, it should be an opt-in option that a user can set

**Comment by darknight009** [comment]
How should the case for directed_star_graph be handled where both bidirectionality and inward are passed. For eg. directed_star_graph(num_nodes = 5, bidirectional=True, inward= True). Does bidirectional override inward?

**Comment by mtreinish** [comment]
Hmm, I forgot about that. I'll defer to you on that as long as it's documented clearly. Either we have one flag take precedence over the other or raise an exception. It doesn't really matter as long as we make it clear what the behavior is in that edge case (and probably have a test asserting that behavior too).

**Comment by darknight009** [comment]
Ok proceeding with precedence of bidirectional over inward.
