### ISSUE TITLE
Add functions to get k-core of a graph

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#193]
### What is the expected enhancement?

This is to add new functions to retworkx's algorithm library to get a k-core number dictionary from a graph. This is similar to networkx's `core_number` https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.core.core_number.html  or graph_tool's `kcore_decomposition`: https://graph-tool.skewed.de/static/doc/topology.html?highlight=kcore_decomposition#graph_tool.topology.kcore_decomposition

**Comment by Chriscrosser3310** [comment]
@mtreinish I’ll be working on this one!
