### ISSUE TITLE
Support devices with Apple M1 chip

### ISSUE THREAD

**Issue by swhiteCQC** [Qiskit/retworkx#231]
### What is the expected enhancement?
Publish a version of retworkx which supports Apple's new M1 chip so it can be installed via pip.

**Comment by swhiteCQC** [comment]
Thanks for the response, I appreciate we're still at fairly early days but thought it would be good to get it on your radar. I was having issues when retworkx was a transitive dependency but just got it to build from source as you suggested and it seems to be working.

**Comment by mtreinish** [comment]
I've added the job to build an arm64 macOS wheel at release time. The next retworkx release, [0.8.0](https://github.com/Qiskit/retworkx/milestone/4), will also publish a python 3.9 arm64 macOS wheel. I'm hoping to have the release ready in the next couple of weeks (the only blocker for it right now is #229)
