### ISSUE TITLE
Expand isomorphism functions

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#268]
### What is the expected enhancement?

After #267 fixes the issues we had the stable graph and vf2 we should expand the isomorphism apis to cover a wider use case. Right now retworkx has 2 functions `is_isomorphism` and `is_isomorphism_node_match` which only works with the `PyDiGraph` class. We should expand these to include functions for `PyGraph` and also for edge matching too. This will require updating the dag isomorphism module to work with petgraph traits instead of fixed type PyDiGraph. 

It might make sense to combine the functions and just make 2 is_isomorphic functions (one for PyGraph the other for PyDiGraph) that have optional kwargs for node and edge matching functions. The one thing we'll need to keep in mind is backwards compatibility because we can't break existing users passing `PyDiGraph` objects to `retworkx.is_isomorphic` and `retworkx.is_isomorphic_node_matching` so if we change the python functions exposed by rust we'll likely need compatibility wrapper functions in the python to adapt existing users to the new way.

**Comment by georgios-ts** [comment]
Looking at petgraph implementation, they have made recently `is_isomorphic` generic with traits that `PyGraph` and `PyDiGraph` implement. But it's not in 0.5.1 release. So we can either wait for their next release or "copy" their source code for now.

**Comment by mtreinish** [comment]
We'll probably want to update our fork with the changes that they made since 0.5.1. I think that we'll still need to keep it forked because IIRC the matching functions passed into is_isomorphic in petgraph don't expect a `Result` return, but because we call python we need to keep that result (because a `PyResult` error is a python exception) so that we can return exceptions to the user if they're raised inside the matching functions.

**Comment by georgios-ts** [comment]
Cool. I am working on this.
