### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#328]
### What is the expected enhancement?

As we've been rapidly growing the functionality in retworkx the flat docs structure we were using before doesn't really scale. Before we push out the 0.9.0 we should work on reorganizing the documentation. The basic structure I had in mind was at the top level:

- README
- Graph Classes
- Algorithms
 -  Universal Functions and functions that are only applicably to single type
- Generators and Random Graph functions
- Visualization
  - Visualization Functions
  - Layout Functions
  - Examples (this can be in a follow up since we'd have to write all of these)
- Detailed API Docs
  - Per graph type algorithm/functions
  - custom return types
  - exceptions

But this isn't set in stone, that's just the idea I had in my head, feel free to propose alternative structures. The key here though is to make the docs organization a bit more clear.

As part of this we also should update the graph class docstrings to include explicit mention that node and edge indices are stable unique identifiers of a node or edge for the lifetime of the graph. This isn't really explicitly called out anywhere and it's very important.

**Comment by IvanIsCoding** [comment]
I will work on this. I will start by splitting the Detailed API docs (`graph_*`, `digraph_*` and methods that are less important for the user let's say) from the Algorithms section.
