### ISSUE TITLE
Add `random_geometric_graph`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/retworkx#340]
### What is the expected enhancement?

It would be great if retworkx has a compatible function with `nx.random_geometric_graph`
https://networkx.org/documentation/stable/reference/generated/networkx.generators.geometric.random_geometric_graph.html
This is not urgent. We can generate a random graph in a simpler way.

It is used for random instance generation for some graph problems.
https://github.com/Qiskit/qiskit-optimization/blob/186e63fe411d0d9b9999b3b538162635be45f550/qiskit_optimization/applications/tsp.py#L137
https://github.com/Qiskit/qiskit-optimization/blob/186e63fe411d0d9b9999b3b538162635be45f550/qiskit_optimization/applications/vehicle_routing.py#L243

Related to https://github.com/Qiskit/qiskit-optimization/pull/150

**Comment by georgios-ts** [comment]
We recently added this function #295 . It will be in the next release.

**Comment by t-imamichi** [comment]
Thanks! I didn't notice it
