### ISSUE TITLE
Rename `edge_list` arg with `edgelist` to be compatible with networkx

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/retworkx#341]
### What is the expected enhancement?

`mpl_draw` has an argument `edge_list` https://github.com/Qiskit/retworkx/blob/885f2de1588dc983591563f94b2ddcada443b3b2/retworkx/visualization/matplotlib.py#L101

The same argument has name `edgelist` in networkx
https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html

Related to https://github.com/Qiskit/qiskit-optimization/pull/150

**Comment by t-imamichi** [comment]
I see. `edge_list` makes more sense. I don't think you need to rename it; but it might be good to write a notice in the networkx users guide.

**Comment by mtreinish** [comment]
Ok sure, I'll push another PR updating the `networkx.rst` guide to have a section about visualizations.
