### ISSUE TITLE
Add `to_numpy_array` or `to_numpy_matrix`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/retworkx#342]
### What is the expected enhancement?

It would be great if retworkx supports `to_numpy_array` or `to_numpy_matrix`.
It is used in a tutorial of qiskit-optimization.
https://github.com/Qiskit/qiskit-optimization/blob/main/docs/tutorials/06_examples_max_cut_and_tsp.ipynb
It is not urgent because we can implement a utility function in Python.

Related to https://github.com/Qiskit/qiskit-optimization/pull/150

**Comment by georgios-ts** [comment]
There is an `adjacency_matrix` function. See https://qiskit.org/documentation/retworkx/stubs/retworkx.adjacency_matrix.html#retworkx.adjacency_matrix

**Comment by t-imamichi** [comment]
Thank for your information. It would be great if it is mentioned in https://qiskit.org/documentation/retworkx/networkx.html
