### ISSUE TITLE
Add option to `PyDiGraph.to_undirected()` to set multigraph false

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#369]
### What is the expected enhancement?

Right now the `PyDiGraph.to_undirected()` method unconditionally sets the multigraph option to True (https://github.com/Qiskit/retworkx/blob/main/src/digraph.rs#L2317) it would be nice to have an option to control this behavior. This would be useful for directed graphs with bidirectional edges to condense that into a single edge in the undirected output from the method.

**Comment by georgios-ts** [comment]
and how we would handle the weight data in the bidirectional/parallel edges?

**Comment by mtreinish** [comment]
Yeah a callable would work. The way this would be handled by the default graph api for when multigraph is `False` is that the newer edge takes priority. So we could just update the loop over edge references in the function to check if an edge exists and if it does update the weight. The only issue there is with edge removals the loop over the edge references won't necessarily be in creation order so that might not be ideal.
