### ISSUE TITLE
retworkx.generators.hexagonal_lattice_graph does not generate consecutive nodes

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/retworkx#373]
### Information

- **retworkx version**: main
- **Python version**: 3.8

While generating `hexagonal_lattice_graph` I noticed that the generated node indexes are not consecutive. This seems unexpected to me.

### What is the current behavior?

```python
import retworkx
G = retworkx.generators.hexagonal_lattice_graph(10, 10)
offset = 0
for i, j in enumerate(G.node_indexes()):
    if i+offset != j :
        offset += 1
        print(i, 'is missing')
```
```
21 is missing
219 is missing
```

### What is the expected behavior?

Consecutive node indexes.

**Comment by mtreinish** [comment]
It is a documented limitation: https://qiskit.org/documentation/retworkx/stubs/retworkx.generators.hexagonal_lattice_graph.html#retworkx.generators.hexagonal_lattice_graph but I agree it would be better to have all the nodes in order.

It was something I raised in review https://github.com/Qiskit/retworkx/pull/277#discussion_r600415023 and it apparently wasn't a straightforward to fix. But if you have a solution for doing this I think it would definitely be a welcome fix.
