### ISSUE TITLE
PyGraph dijkstra path functions return incorrect path in some cases

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#387]
### Information

- **retworkx version**: 0.9 and `main` 
- **Python version**: 3.9
- **Rust version**: 1.53.0
- **Operating system**: Linux

### What is the current behavior?
Running this code:

```python
        graph = retworkx.PyGraph()
        graph.add_node(None)
        graph.extend_from_weighted_edge_list([
            (1, 2, 10),
            (2, 3, 10),
            (3, 4, 10),
            (4, 5, 10),
            (5, 6, 10),
            (2, 7, 1),
            (7, 5, 1)
        ])
        graph.remove_node(0)
        path = retworkx.graph_dijkstra_shortest_paths(
            self.graph, 5, weight_fn=float, target=3
        )
        print(path)
        expected = {3: [5, 7, 2, 3]}
        assert expected == path
        path = retworkx.graph_dijkstra_shortest_paths(
            self.graph, 3, weight_fn=float, target=5
        )
        print(path)
        expected = {5: [3, 2, 7, 5]}
        assert expected == path
```

fails. The returned paths look like they're not using the weight correctly as it's outputting a path of `[5, 4, 3]` which has a weighted distance of 20 vs the expected path `[5, 7, 2, 3]` which has a weighted distance of 12.

The interesting and unexpected thing is that the distance function is returning the expected correct result and the underlying rust code is the same function.

### What is the expected behavior?

The expected path should take into account the weight and be returned correctly.

**Comment by IvanIsCoding** [comment]
https://github.com/Qiskit/retworkx/blob/main/src/dijkstra.rs#L138-L142 is a great candidate for originating this bug

**Comment by mtreinish** [comment]
Yeah, that's the bug. I'm working on the patch now. So many of our tests for this were just wrong it's kind of upsetting actually how off everything was.
