### ISSUE TITLE
Add minimum steiner tree function

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#389]
### What is the expected enhancement?

Add a minimum steiner tree function equivalent to networkx's `steiner_tree()` function: https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.steinertree.steiner_tree.html#networkx.algorithms.approximation.steinertree.steiner_tree

The source can be found here: https://github.com/networkx/networkx/blob/80704838e60327f3e3a292f4fb4812039be843df/networkx/algorithms/approximation/steinertree.py

This will likely need to be done over 3 PRs, one adding `metric_closure()`, one for `edge_subgraph`, and the last combines the first 2 to make the `steiner_tree` function.

**Comment by georgios-ts** [comment]
After reading the original [paper](http://aturing.umcs.maine.edu/~markov/SteinerTrees.pdf), it seems that some steps in the original algorithm are missing from NetworkX function (steps 4 and 5 to be specific). I tried to find an example that breaks the function but couldn't find any. Depending on how you choose the minimum spanning tree in step 3, steps 4 and 5 might be unnecessary.

Although you have almost done all the work in #392, i mention here for future reference that there is a similar algorithm with the same approximation ratio but better runtime complexity (https://people.mpi-inf.mpg.de/~mehlhorn/ftp/SteinerTrees.pdf).
