### ISSUE TITLE
Subgraph isomorphism fails with parallel edges

### ISSUE THREAD

**Issue by georgios-ts** [Qiskit/retworkx#429]
### Information

- **retworkx version**: main
- **Python version**: Any
- **Rust version**: Any
- **Operating system**: Any

### What is the current behavior?
`is_subgraph_isomorphic` returns `True` even in cases it shouldn't. This happens if the input "small" graph have parallel edges.

### What is the expected behavior?
Handle correctly graphs with parallel edges.

### Steps to reproduce the problem
```python
import retworkx as rx

first = rx.PyGraph()
first.extend_from_edge_list([
    (0, 1), (1, 2), (2, 3)
])
second = rx.PyGraph()
second.extend_from_edge_list([
    (0, 1), (0, 1)
])
rx.is_subgraph_isomorphic(first, second)
---
True
```

**Comment by mtreinish** [comment]
Fixing this definitely seems worth including in a 0.10.2 release.

**Comment by georgios-ts** [comment]
UPDATE:
Even `retworkx.is_isomorphic` fails with parallel edges if an `edge_matcher` is specified.
An example:
```python
import retworkx as rx

graph = rx.PyGraph()
graph.extend_from_weighted_edge_list([
    (0, 1, 'a'), (0, 1, 'b'), (1, 2, 'c')
])

rx.is_isomorphic(graph, graph,
                 edge_matcher=lambda x, y: x == y)
----
False
```
