### ISSUE TITLE
Add method for replacing block with node in graph

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/retworkx#476]
### What is the expected enhancement?

In https://github.com/Qiskit/qiskit-terra/pull/7185 terra is adding a method that replaces a block of graph nodes (as found with [`collect_bicolor_runs()`](https://qiskit.org/documentation/retworkx/stubs/retworkx.collect_bicolor_runs.html?highlight=collect_#retworkx.collect_bicolor_runs)) with a single node. The idea is that the block is consolidated to an equivalent single node. That PR adds a function to terra's dag class, `replace_block_with_op()` that iterates over all the predecessors and successors outside the block and adds equivalent edge to and from the replacement node. This should be easy to implement in retworkx natively as a method on `PyDiGraph` and `PyGraph` as it's primarily a function of the graph and doesn't involve any python interaction (except for the creation of the replacement node) so we should add a function for this to retworkx. The basic idea would be to add something like: `fn replace_block_with_node(&mut self, py: Python, block_nodes: Vec<usize>, node: usize)` to the `pymethods` of the graph classes which will do the copying of edges to and from the `block_nodes` to `node` and remove `block_nodes` from the graph.

**Comment by szhorvat** [comment]
If I understand the request, the standard name for this is "vertex contraction".
