### ISSUE TITLE
[joss] retworkx namespace is not clean

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#502]
### Information

- **retworkx version**: 0.10.2

### What is the current behavior?

The `retworkx` namespace contains things that do not belong to `retworkx`. These show up when using auto-completion (type `retworkx.`, tab), which is a usual way to interactively explore the library. It would be nice to make sure that only those things show up which are actually means to be public retworkx symbols.

For example, `rewtorkx.sys` and `retworkx.functools` should probably not be present.

**Comment by mtreinish** [comment]
This is unfortunately an aspect of how python works and is not something we can really fix in retworkx. To make retworkx work we need to import some python standard library modules in the root of the package (in this case `sys` to add our `generators` submodule to the proper path and `functools` to do the dispatch for universal functions). The way python import works those imports get set as attributes on the module (which is itself a python object). So whichever tool you're using for tab completion (I assume `jedi`) is looking at the attribute lists on that module object (i.e. doing `dir(retworkx)`) and it's listing all of those local import attributes. You can see this in other libraries too, for example `numpy` if you run `dir(numpy)` or tab complete on it you'll see there are also things there like `numpy.sys` and `numpy.warnings` which are the standard library modules [sys](https://docs.python.org/3/library/sys.html) and [warnings](https://docs.python.org/3/library/warnings.html).

**Comment by szhorvat** [comment]
Thanks for the explanation and feel free to close this issue. I am far from a Python expert.
