### ISSUE TITLE
[joss] lexicographical_topological_sort() docs are unclear

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#506]
I was unable to tell what `lexicographical_topological_sort()` does after looking at its documentation. As far as I am aware, "lexicographical topological sorting" is not standard terminology. It would be good to explain it.

I looked up the corresponding networkx function, and now I can see that this function is for breaking ties in the ordering based on an additional comparison. This was not clear.

**Comment by mtreinish** [comment]
I just pushed up a PR improving the docstring here: https://github.com/Qiskit/retworkx/pull/510
