### ISSUE TITLE
[joss] How to get edges incident to a vertex?

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#509]
I was wondering about how one might implement certain graph algorithms, such as basic graph traversal, or obtaining a cycle basis in terms of edges, perhaps compute the edge-cycle matrix (see #505). 

For such operations, it is necessary to be able to access the incident edges of a node (similar to `.neighbors()` or `.adj()` but returning edges). How can I do this?

**Comment by IvanIsCoding** [comment]
For directed graphs, the methods you are looking for are:
* [`PyDiGraph.out_edges`](https://qiskit.org/documentation/retworkx/stubs/retworkx.PyDiGraph.out_edges.html#retworkx.PyDiGraph.out_edges): for outgoing edges
* [`PyDiGraph.in_edges`](https://qiskit.org/documentation/retworkx/stubs/retworkx.PyDiGraph.in_edges.html#retworkx.PyDiGraph.in_edges): for incident edges

To achieve an equivalent behaviour on undirected graphs, the current best way is to:
* Call [`PyGraph.neighbors`](https://qiskit.org/documentation/retworkx/stubs/retworkx.PyGraph.neighbors.html#retworkx.PyGraph.neighbors), as you pointed out
* Then call [`PyGraph.get_edge_data`](https://qiskit.org/documentation/retworkx/stubs/retworkx.PyGraph.get_edge_data.html#retworkx.PyGraph.get_edge_data) with the node indices
