### ISSUE TITLE
[joss] dfs_edges() invalid result on multigraphs

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#516]
`dfs_edges()` does not seem to support multigraphs properly:

```
g = rx.PyGraph()
g.extend_from_edge_list([(0,0), (0,1), (1,2), (1,2), (2,3)])

print(rx.dfs_edges(g, 0))
```

```
EdgeList[(0, 1), (1, 2), (2, 3)]
```

I would expect every edge to be traversed, since this function specifically returns edges (not merely nodes). One possible correct result would be `(0,0), (0,1), (1,2), (2,3), (1,2)`.

**Comment by szhorvat** [comment]
This is related to #512.

**Comment by georgios-ts** [comment]
`dfs_edges` returns only edges that are part of the DFS tree. Documentation should be more clear on this.

**Comment by szhorvat** [comment]
I see, so this is basically a spanning tree function, comparable to `minimum_spanning_edges()`. In that case the behaviour is correct, but the docs should really be updated. Now they state:

> Get edge list in depth first order

which I assumed referred to the edge list of the graph.
