### ISSUE TITLE
[joss] unweighted_average_shortest_path_length() mishandles disconnected graphs

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#524]
`unweighted_average_shortest_path_length()` considers the distance between nodes not reachable from each other to be 0. While this is [documented](https://qiskit.org/documentation/retworkx/stubs/retworkx.unweighted_average_shortest_path_length.html#retworkx.unweighted_average_shortest_path_length), it is simply incorrect, and counter to any reasonable interpretation of the concept. I would consider this a bug because it will confuse users, or worse: lead them to incorrect results in their analysis.

**Comment by szhorvat** [comment]
In the docs, the formula should probably read $\sum_{s,t \in V, s \ne t}$

**Comment by georgios-ts** [comment]
We discussed this in https://github.com/Qiskit/retworkx/pull/403#discussion_r690747156 and ended up using the definition found in Wikipedia https://en.wikipedia.org/wiki/Average_path_length#Definition.
What's a reasonable output in your opinion for disconnected graphs? Infinity or just throw an error?

**Comment by szhorvat** [comment]
Don't rely on Wikipedia for network analysis stuff, it is full of mistakes and mischaracterizations.

In situations like this, I loosely rely on principles like the following three (in decreasing order of important):

 1. **Correctness and predictability.** There should be a way for the user to tell that the graph was disconnected. This can be achieved either by throwing an error or by returning infinity.
 
 2. **Generality.** Instead of just failing in edge cases, try to come up with a reasonable definition of the concepts. In this case, infinity is a reasonable value for the average path length when the graph is disconnected. It is consistent with most properties one would expect to hold for the average path length. If a user does further arithmetic with the result of the average path length function, things will more or less work and produce similarly reasonable results even if the result was infinity. 
 
    For me, this principle chooses between throwing an error or returning infinity. Sometimes there are technical limitations which make this impossible though, for example the result may be an integer data type which cannot represent infinity.

    I would apply the same principle to decide what to return when a null graph, or a singleton graph is passed in. Currently, retworkx returns NaN and 0, respectively. I would have chosen the same values.

3. **Flexibility.** Anticipate use cases, and try to satisfy as many as possible. Maybe you can add a flag which controls whether the average is taken for all `(s,t)` pairs, or only those `(s,t)` pairs for which `t` is reachable from `s`.

This is how I ended up with the current average path length behaviour in igraph when I modified it recently. 

https://igraph.org/c/html/latest/igraph-Structural.html#igraph_average_path_length

Of the above points, I would consider 1. critically important (don't return wrong results with no warning), 2. a good (but debatable) design, and 3. a nice to have extra.
