### ISSUE TITLE
import retworkx error on compute canada hpc

### ISSUE THREAD

**Issue by Shreya202193** [Qiskit/retworkx#529]
"import retworkx" returns:

from .retworkx import *
ModuleNotFoundError: No module named 'retworkx.retworkx'
doest not resolve after ''pip install retworkx"

python: 3.8.10, 
compute canada hpc, node graham 
issue did not resolve after upgrading to python 3.9

**Comment by IvanIsCoding** [comment]
Can you check if there is a directory named `retworkx` on the same directory you are trying to execute the Python code? If there is, that is the problem.

Python imports will try to import from that local folder first, and Python will not find the compiled binary, hence the error. This will happen in all Python versions.

The fix is simple though: execute your code in another place without a directory named `retworkx`. For example:
```bash
cd ..
python your_old_directory/your_code.py
```

Should work

**Comment by Shreya202193** [comment]
no there isn't a directory named retworkx

**Comment by mtreinish** [comment]
Unfortunately there's not a lot to go on here. @IvanIsCoding's suggestion is the normal/most common cause of this, but if there isn't a directory named `retworkx` in your current working directory then it's gonna be hard for us to provide suggestions. What this error is saying is that the compiled binary file for retworkx isn't living next to the python module for retworkx. Normally if you look at retworkx's installed package you'll see a directory that contains files like:
```
retworkx/
    __init__.py
    retworkx.cpython-39-x86_64-linux-gnu.so
```

(note there are more files there and `retworkx.cpython-39-x86_64-linux-gnu.so` can be anything `retworkx*.so` as the exact filename is platform dependent)

The error message is saying in your python environment you've got the directory and the `__init__.py` file, but the `retworkx*.so` isn't present.

Without having access to the system to see your python environment it's hard to debug what is causing the binary to be missing. The only suggestion I have is general python stuff, make sure you have the latest version of pip installed with `pip install -U pip` and also you to try creating a fresh virtual environment and installing into that. Basically running something like:

```
python -m venv foo
foo/bin/pip install -U retworkx
foo/bin/python -c 'import retworkx;print(retworkx.__version__)
```
which should hopefully print `0.10.2`.

**Comment by Shreya202193** [comment]
Finally,  I was able to make it works by installing setuptools-rust and running `python ./setup.py install`.

More info there : https://pypi.org/project/setuptools-rust/

**Comment by mtreinish** [comment]
Cool I'm glad you got it working.

Although, I'm surprised that setuptools-rust was necessary though if you're installing from pypi. We publish precompiled packages to pypi on release and setuptools-rust is only needed if you're building retworkx from source.

**Comment by mtreinish** [comment]
Since this has been resolved I am going to close this issue. But please feel free to reopen it if there is anything else to discuss here.
