### ISSUE TITLE
Implement bellman ford negative cycle finding

### ISSUE THREAD

**Issue by leehonan** [Qiskit/retworkx#592]
### What is the expected enhancement?
Implement bellman ford negative cycle finding, as a convenience so users don't need to roll their own.  See NetworkX equivalent at https://networkx.org/documentation/latest/_modules/networkx/algorithms/shortest_paths/weighted.html#find_negative_cycle

**Comment by mtreinish** [comment]
Thanks for opening an issue, this should be too hard to implement and include in the next release.

@IvanIsCoding I know you were talking about adding a bellman ford function at one point a while ago. Did you ever start that?

**Comment by IvanIsCoding** [comment]
> Thanks for opening an issue, this should not be too hard to implement and include in the next release.
> 
> @IvanIsCoding I know you were talking about adding a bellman ford function at one point a while ago. Did you ever start that?

I had a draft of [SPFA](https://en.m.wikipedia.org/wiki/Shortest_Path_Faster_Algorithm#:~:text=The%20Shortest%20Path%20Faster%20Algorithm,that%20contain%20negative%2Dweight%20edges.), which in general would be faster than Bellman-Ford. I'll try to port the code to `retworkx-core` and make a PR

**Comment by leehonan** [comment]
Thanks very much! Would SPFA be faster in all cases, or would the optimisation be less useful for a small graph etc?
