### ISSUE TITLE
MacOS older version support in wheels

### ISSUE THREAD

**Issue by henryiii** [Qiskit/retworkx#62]
### What is the expected enhancement?

I was helping someone install this library and realized that they had macOS 10.12 + Conda Python 3.7, and couldn't pull the wheels since they are 10.13+ (intel) and 10.15+ (normal). Could the `MACOSX_DEPLOYMENT_TARGET` be set to 10.12 or 10.9? I'm guessing it is not set at all, due to the 10.15 in the wheel. If not, is there a reason it can't be lowered?

**Comment by henryiii** [comment]
Note: In CIBUILDWHEEL, regardless of what the current documentation seems to claim, `MACOSX_DEPLOYMENT_TARGET` is not set automatically, and it generally always should be set by hand.

**Comment by mtreinish** [comment]
Thanks for the suggestion, I wasn't aware of that env variable. As a non-mac user I wasn't sure how to control the compat level and the reason for the different wheels on the current version on pypi was ci env differences (azure pipelines vs travis). I agree we should do this as I want to make sure we offer widely compatible wheels for as many platforms as we can for this (the nightly rustc requirement is difficult for some users unfamiliar with the rust ecosystem). I'll push up a pr tomorrow to experiment with setting that env variable in the cibuildwheel environment to see if I can get it to build wheels targeting 10.9.

**Comment by mtreinish** [comment]
Ok, I've pushed up a PR (#63) to fix this. I also pushed up test commit to manually trigger the macOS wheel builds to test this. Based on the output of the ci job it looks like it's working:

https://dev.azure.com/qiskit-ci/retworkx/_build/results?buildId=11655&view=logs&j=59072c2d-ff9c-5ba9-5217-fae5d67698fb&t=e64845d4-b26a-5b36-9ae2-80aaa975f01a&l=523

If you want to test the wheels built by the job are hosted here: https://dev.azure.com/qiskit-ci/retworkx/_build/results?buildId=11655&view=artifacts&type=publishedArtifacts (there is a download icon that will appear when you hover your mouse over the drop line, the azure pipelines ui leaves something to be desired) if you want to verify that these work on an older macOS version. Once the PR merges I will soon push out a 0.3.4 release to get the updated wheels on pypi.

**Comment by mtreinish** [comment]
Just wanted to leave a note here, the 0.3.4 release is up on pypi now: https://pypi.org/project/retworkx/0.3.4/#files and the macOS wheels were built with a 10.9 target so local compilation should no longer be required to install the package on older versions of macOS.
