### ISSUE TITLE
Proposal Plan To Rename Library

### ISSUE THREAD

**Issue by IvanIsCoding** [Qiskit/retworkx#641]
## Proposal Plan To Rename Library

This is a proposal to give a new name for the library. After our submission to the Journal of Open Source Software (https://github.com/openjournals/joss-reviews/issues/3968), one reviewers and the core developers pointed that the name retworkx is very close to NetworkX. As a courtesy to the NetworkX developers, I suggest to change the name of the library.

### Choose a new name

The first step is to choose a new name for the library. Some suggestions from me and :

* reseaux
* ~qisnet~
* ~networkQIS~
* rustworkx
* ~rustynets~
* ~netrust~

We are also open to suggestions.

### Release the next version package under the new name

The second step is to release the next version of the package (which as of now would be 0.12) under the new name. This entails a PR renaming all of our references from retworkx to the new package name we agree on. 

This will requires us to:
* Create a new package on PyPI under the new name
* Create a new crate on crates.io under the new name
* Create new documentation links in https://qiskit.org/documentation
* Rename our Github repository
* Publish a new version of the pre-print on arXiv
* Update our record on Zenodo

### Release new versions of retworkx packages depending on the new package

The third step is to provide support for retworkx. Ideally, we should just deprecate the name but continue supporting it for at least some releases  (I suggest two relases, which would be 0.12 and 0.13).

This can be done by making retworkx depend on the new package. For example, retworkx 0.12.0 would depend on the 'newpackagename' 0.12.0', retworkx 0.12.1 would depend on 'newpackagename' 0.12.1 and so on. This can be accomplished by importing from 'newpackage'. Because most of our code is in Rust, we just need to change a couple retworkx Python files to something along the lines of:

```python
from newpackagename import *
```

This step also requires us to:
* Add a disclaimer on README and PyPI that retworkx was renamed and that releases under the old name will stop after a couple versions
* Redirect links from https://qiskit.org/documentation/retworkx to the new documentation

**Comment by mtreinish** [comment]
Well for me I think either `reseaux` (which I'm leaning towards) or `rustworkx` are what we should use. That way we can keep the `rx` abbreviated import. So we should decide on a name between those. I definitely don't want to switch to any of the qis names as retworkx is hardly limited to quantum applications.  @georgios-ts @itoko @lcapelluto what are your preferences here?

**Comment by mtreinish** [comment]
I put together a commit doing the name migration to reseaux mostly to test the migration path and have idea on how to maintain backwards compatibility during the migration period: https://github.com/mtreinish/retworkx/commit/8a2245bd9558a5f01d7b217a69768d71aeaab36f it's still missing the documentation redirect publishing (which I'll add to the branch later) along with the long tail of renaming things manually (like repo, slack channel, irc channel, etc).

I'd like to wait some more time to collect more opinions on the name to make sure there is a wider consensus on using reseaux before I open a PR doing the migration.

**Comment by itoko** [comment]
I like `reseaux` too, (or `rustworkx`, which has a better Google searchability).

**Comment by IvanIsCoding** [comment]
> For the specific steps, I think there are a couple of things we'll need to do differently than the plan you outlined. First just doing a compat shim with a `*` import isn't actually sufficient. This is mostly because of imports of subpackages, such as `from retworkx.generators import star_graph` , which won't work with a `*` import. I have a pattern to resolve this though we can use a meta importer to add a redirect from retworkx imports to the new namespace (we'll basically just copy what I did in [Qiskit/qiskit-terra#5089](https://github.com/Qiskit/qiskit-terra/pull/5089) although change the fallback behavior to prefer the redirect). With that hook in place I think it might be easier to just publish both packages side by side with identical code. So for 0.12.0 we publish both retworkx and the new name as identical packages.
> 

You are correct about the imports, your solution is better and I am glad we can reuse the code from qiskit_aer.

I still think we should make `retworkx` depend on `reseaux` (or any new name), it has some advantages. This was easy to build on top of the PR you wrote, I just had to change a couple lines: https://github.com/IvanIsCoding/retworkx/blob/9b75cfccc8f6b6c4c6b55740cec204ddf79cfce8/setup.py

Some advantages are:
* `reseaux` will be on the dependency tree of packages that use the latest release of `retworkx`, so doing `pip install reseaux` does not have to download the same code twice
* it allows `retworkx<=0.11` to coexist with `reseaux>=0.12` in the same machine, nothing breaks
* it disallows cases like `retworkx==0.12.0` and `reseaux==0.13` being installed in the same machine, as the version of `retworkx` is tied to `reseaux`

**Comment by enavarro51** [comment]
Just thought I'd give you my 2-cents on the name change. The French word reseaux has an acute accent on the first e, so it's pronounced ray-zo. If I didn't see the accent, I might pronounce it more like ru-so. I'm sure there is no need for the accent as a product name, but there might be some French who would object. I also know we have an international following, and I assume most would know a lot more English than French, which might make them (and some American/English) try to pronounce it as ru-zooks, or some such.

I like rustworks or rustworkx, but there apparently is a game called Rust, and there's a website, [rustworks.org](http://rustworks.org/), that is for gamers to meet up and discuss the game. There was also a Github repo called Rustworks that is a Rust language OS for Numworks, whatever that is.

The only items for rustworkx are Rust Worx and Rust Werx, which both seem to be automotive related, so no problem there. I personally like rustworkx. It's pretty descriptive, and it has a gritty, steel mill quality, that might be a good visual for people to remember it. Also pronunciation should be no more of a problem for anyone than networkx is.

**Comment by 1ucian0** [comment]
`rustworkx`!

**Comment by mtreinish** [comment]
So after talking to a number of users I'm thinking we should rename to rustworkx instead of reseaux. Everyone liked the reseaux name once they understood it, but since English is the language for retworkx most people ended up confused by the reseaux name initially, not knowing French. While rustworkx being closer to the original retworkx name was seen as an easier transition to make. I'll start adapting my commit to use rustworkx and push that as a PR.
